/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#213145',
        'on-secondary-container': '#5c647a',
        'outline-variant': '#c3c6d7',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary-fixed': '#00201c',
        'on-error-container': '#93000a',
        'surface-container': '#e5eeff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'background': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#4fdbc8',
        'on-secondary': '#ffffff',
        'tertiary': '#006056',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'tertiary-container': '#007b6e',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'on-surface-variant': '#434655',
        'primary-fixed': '#dbe1ff',
        'primary-container': '#2563eb',
        'secondary-container': '#dae2fd',
        'on-tertiary-container': '#b1fff1',
        'secondary-fixed': '#dae2fd',
        'surface-variant': '#d3e4fe',
        'primary': '#004ac6',
        'on-primary-container': '#eeefff',
        'secondary-fixed-dim': '#bec6e0',
        'on-surface': '#0b1c30',
        'secondary': '#565e74',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#b4c5ff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-primary': '#b4c5ff',
        'error': '#ba1a1a',
        'outline': '#737686',
        'on-tertiary': '#ffffff',
        'surface': '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed': '#131b2e',
        'surface-tint': '#0053db',
        'tertiary-fixed': '#71f8e4',
        'on-tertiary-fixed-variant': '#005048',
        'on-primary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#3f465c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'xs': '4px',
        'gutter': '24px',
        'base': '8px',
        'max-width': '1280px',
        'md': '24px',
        'margin-mobile': '16px',
        'sm': '12px',
        'xl': '64px',
        'lg': '40px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      maxWidth: {
        'max-width': '1280px',
      },
    },
  },
  plugins: [],
};
